Issue1150 Use execute_action_internally
OpenSlides/openslides-backend pull request #1164
Opened 2022-01-19 17:47 UTC by r-peschke

Missing part from review of #1151
Maybe there is more to do on meeting.clone problem:

motion/48: Invalid fields workflow_id (value: 5)  After simple amendment motion on new crated meeting

2022-01-20 07:50 UTC, jsangmeister requested changes
You can do the same in the test below ( and maybe in other tests there too?)

2022-01-20 07:52 UTC, jsangmeister commented
> motion/48: Invalid fields workflow_id (value: 5) After simple amendment motion on new crated meeting

Can you evaluate when and why this problem occurs? It looks like the action data field `workflow_id` is not correctly deleted from the instance, but on a quick glance it seems like it is always correctly `pop`ed out.

2022-01-20 08:30 UTC, r-peschke commented
> > motion/48: Invalid fields workflow_id (value: 5) After simple amendment motion on new crated meeting
> 
> Can you evaluate when and why this problem occurs? It looks like the action data field `workflow_id` is not correctly deleted from the instance, but on a quick glance it seems like it is always correctly `pop`ed out.

It's a bug report by @emanuelschuetze : Create a meeting, write a motion and an motion amendment. The error should occur on meeting.clone, but doesn't. I asked him to help.

2022-02-02 11:49 UTC, jsangmeister approved these changes

2022-02-02 11:56 UTC, merged