Add set_as_template to meeting.{create,update}
OpenSlides/openslides-backend pull request #1219
Opened 2022-02-16 12:30 UTC by jsangmeister

closes #1214

2022-02-17 11:22 UTC, r-peschke reviewed
Technically I would approve the changes. But ...

### We should not allow a template-meeting to be used as regular meeting.
A template meeting should not be changed by daily work on motions, polls etc.

### Requirements and database structure

case 1:
Requirement: Each committee can define template_meetings, which are available for the whole organization
With this requirement we have to read all committees with the field `template_meeting_ids`, to present all organization wide meeting-templates.

case 2:
Requirement: Each committee can define meeting-templates only for themselves.   
The design fits best for this case

case 3:
Requirement: More flexibility with meeting-templates for the whole organization or the committee itself or a dedicated list of committees. There are some combinations possible. 
For this case we should define the exact requirement and create a database structure.

2022-02-17 13:09 UTC, jsangmeister commented
> ### We should not allow a template-meeting to be used as regular meeting.
> A template meeting should not be changed by daily work on motions, polls etc.

How do you want to prevent this? The user still needs to be able to edit the template and everything in it (motions, agenda, etc.), so it must be usable just like a "real" meeting. I think it is the user's responsibility to not use a template meeting as a "regular" one. Only thing we could do is display a warning, but this is would be a client change...

2022-02-17 15:09 UTC, r-peschke requested changes

2022-02-17 15:11 UTC, r-peschke commented
> > ### We should not allow a template-meeting to be used as regular meeting.
> > A template meeting should not be changed by daily work on motions, polls etc.
> 
> How do you want to prevent this? The user still needs to be able to edit the template and everything in it (motions, agenda, etc.), so it must be usable just like a "real" meeting. I think it is the user's responsibility to not use a template meeting as a "regular" one. Only thing we could do is display a warning, but this is would be a client change...

This is the user's responsibility! He want's and can change the template-meeting.

2022-02-17 15:11 UTC, jsangmeister commented on global/data/example-data.json
> -            "template_meeting_ids": [],
No, since there are no templates currently in use, this should be fine

2022-02-21 12:10 UTC, ostcar commented
See https://github.com/OpenSlides/openslides-autoupdate-service/pull/423 for the autoupdate-service.

Please ping me, if the models.yml is changed again in this PR

2022-02-22 13:07 UTC, jsangmeister commented
Added migration. Only works with https://github.com/OpenSlides/openslides-datastore-service/pull/180

2022-02-23 10:47 UTC, r-peschke approved these changes

2022-02-23 13:17 UTC, merged