Add field weight to group.
OpenSlides/openslides-backend pull request #1226
Opened 2022-02-18 13:16 UTC by reiterl

Update tests, data. Write a migration and test.

2022-02-18 17:45 UTC, r-peschke requested changes

2022-02-18 17:45 UTC, r-peschke commented on global/data/example-data.json
> +	    "weight": 1,
could you please set the indent to 4?

2022-02-21 09:35 UTC, reiterl commented on global/data/example-data.json
> +	    "weight": 1,
Updated the layout.

2022-02-21 09:35 UTC, reiterl commented on global/data/initial-data.json
> +	    "weight": 1,
Updated the layout.

2022-02-21 09:38 UTC, reiterl commented on openslides_backend/action/actions/group/create.py
> +    weight_map: Dict[int, int] = {}
typed it in get_updated_instances.

2022-02-21 09:54 UTC, reiterl commented on openslides_backend/action/actions/group/create.py
> +    weight_map: Dict[int, int] = {}
I simplified the set_weight method, so it no longer need a weight_map.

2022-02-21 09:55 UTC, reiterl commented on openslides_backend/action/actions/group/create.py
> +            max_weight = self.weight_map[meeting_id]
Simplified the code.

2022-02-21 09:55 UTC, reiterl commented on openslides_backend/action/actions/group/create.py
> +        meeting_id = instance["meeting_id"]
Simplified the code.

2022-02-21 10:07 UTC, reiterl commented on tests/system/action/meeting/test_clone.py
> +                "weight": 1,
Add a test.

2022-02-21 10:30 UTC, reiterl commented on openslides_backend/action/actions/group/create.py
> +            max_weight = self.weight_map[meeting_id]
Add two tests to check the weight in multi group creation.

2022-02-21 11:37 UTC, r-peschke approved these changes

2022-02-21 12:35 UTC, merged