Update models.yml for multiple votes per option
OpenSlides/openslides-backend pull request #1266
Opened 2022-03-14 15:01 UTC by MJJojo97

See https://github.com/OpenSlides/openslides-backend/pull/1251

2022-03-14 15:19 UTC, ostcar approved these changes

2022-03-14 15:41 UTC, ostcar requested changes

2022-03-14 15:41 UTC, ostcar commented on global/meta/models.yml
> +    minimum: 1
`restriction_mode: A` is missing

2022-03-14 20:14 UTC, MJJojo97 commented on global/meta/models.yml
> +    minimum: 1
Oh yes. I am very sorry about that!

2022-03-14 20:51 UTC, ostcar commented
Ohh, I see there is a check, that the example_data is valid. I did not realise that. This is strange, because your field is not required. So why do you have to add it to the example data?

Anyway, could you add it?

2022-03-14 23:07 UTC, MJJojo97 commented
Sorry for the inconvenience! I didn't have the full overview on what make-tasks I have to run. Otherwise, I would have seen that problem before.

I hope that everything is working now.

2022-03-15 07:49 UTC, jsangmeister commented
> Ohh, I see there is a check, that the example_data is valid. I did not realise that. This is strange, because your field is not required. So why do you have to add it to the example data?

Because it has a a default value - and yes, I know how strange that sounds :D

> Sorry for the inconvenience! I didn't have the full overview on what make-tasks I have to run. Otherwise, I would have seen that problem before.

No problem, it's a lot one has to take care of when changing the models definition. You can be very happy that no migration is required here :D

2022-03-15 08:01 UTC, jsangmeister approved these changes

2022-03-15 08:16 UTC, merged