Add motion_comment_section actionset with model and tests.
OpenSlides/openslides-backend pull request #127
Opened 2020-09-14 12:49 UTC by reiterl

Add model, action set and tests for motion_comment_section.

2020-09-15 14:07 UTC, jsangmeister requested changes

2020-09-16 08:18 UTC, reiterl commented on openslides_backend/action/motion_comment_section/create_update_delete.py
> +        properties=["read_group_ids", "write_group_ids"]
Done.

2020-09-16 08:39 UTC, reiterl commented on openslides_backend/action/motion_comment_section/create_update_delete.py
> +class MotionCommentSectionActionSet(ActionSet):
I split the ActionSet in three Actions, it simplifies the code, so I checked it in.

2020-09-16 12:05 UTC, jsangmeister requested changes
Adjust to new base test class functions. Rest is good

2020-09-16 13:37 UTC, jsangmeister approved these changes

2020-09-16 13:37 UTC, merged