Opentelemetry
OpenSlides/openslides-backend pull request #1273
Opened 2022-03-21 13:40 UTC by reiterl

2022-03-21 13:45 UTC, reiterl commented
See #1201 for details.

2022-03-21 13:56 UTC, jsangmeister requested changes

2022-03-23 09:53 UTC, reiterl commented on openslides_backend/shared/otel.py
> +        endpoint=get_otel_url(),
Replace the endpoint code here with a default env in the dc.

**Notice:**
To make it run with **tests**, you want to call the init and instruments_requests in __init__ file. The main() function is not called in the pytests. AFAIK.

2022-05-09 10:02 UTC, jsangmeister commented
Seems to not be working in the backend right now. If I run `make run-dev-local-ds-otel` with both this and the datastore checked out to `opentelemetry` side-by-side and then run `pytest`, I only get useless traces from `jaeger-query` in the UI (under http://localhost:16686/) with no spans at all. @peb-adr can you take a look at this and either fix it or tell me what I'm doing wrong? I don't have enough knowledge of otel, unfortunately.

2022-06-08 16:11 UTC, merged