Fix problem with user/meeting_ids of merged users in meeting.import.
OpenSlides/openslides-backend pull request #1370
Opened 2022-06-22 12:51 UTC by reiterl

Use a less deep change to fix the problem. 
Add the test from the issue to show the problem.

2022-06-22 14:15 UTC, r-peschke requested changes

2022-06-23 09:23 UTC, r-peschke approved these changes

2022-06-23 09:23 UTC, r-peschke commented on tests/system/action/meeting/test_import.py
> +    def test_merge_users_check_user_meeting_ids(self) -> None:
> Please, copy the whole test from #1369. It is still the test `test_merge_users_check_committee_and_meeting`, but with more logic and it tests also the committee_ids, that are wrong, too.
I attended the OS3/OS4 workings and fixed the tests. Finally spent more time and fixed the rest also. Now you could review:-)

2022-06-23 11:17 UTC, reiterl commented on openslides_backend/action/actions/meeting/import_.py
> +        for field, entry in relations.items():
Outdated.

2022-06-23 11:18 UTC, reiterl commented on tests/system/action/meeting/test_import.py
> +    def test_merge_users_check_user_meeting_ids(self) -> None:
Outdated.

2022-06-23 11:30 UTC, r-peschke approved these changes
Added a comment as hint for the new code part.
If you don't have more changes, you can merge, otherwise ask again for review

2022-06-23 11:31 UTC, merged