Add replacement_enum to font_$_id and logo_$_id
OpenSlides/openslides-backend pull request #1399
Opened 2022-07-11 12:27 UTC by reiterl

Use it in a check in set_font and set_logo.
Add some tests.

2022-07-11 13:07 UTC, jsangmeister requested changes

2022-07-11 13:07 UTC, jsangmeister commented on openslides_backend/action/actions/meeting/base_set_mediafile_action.py
> +            )
I *think* the relation handling already does this check. Did you try it out without this implementation?

2022-07-11 13:07 UTC, jsangmeister commented on global/meta/models.yml
> +      -  projector_main
```suggestion
      - projector_main
```

2022-07-11 13:29 UTC, reiterl commented on global/meta/models.yml
> +      -  projector_main
Ah, a typo, fixed.

2022-07-11 14:58 UTC, r-peschke requested changes

2022-07-12 05:54 UTC, reiterl commented on tests/system/action/meeting/test_set_font.py
> +        assert model.get("font_$bold_id") == 17
Also assert the template field and use assert_model_exists.

2022-07-12 05:55 UTC, reiterl commented on tests/system/action/meeting/test_set_logo.py
>          assert model.get("logo_$web_header_id") == 17
Assert the template field, too. And use assert_model_exists.

2022-07-12 11:00 UTC, r-peschke approved these changes

2022-07-12 11:13 UTC, merged