Assert that assignment poll history works
OpenSlides/openslides-backend pull request #1455
Opened 2022-09-07 12:54 UTC by jsangmeister

There are already a few tests which test this functionality (that a history entry is created for the content object, in this case the assignment, when the poll is changed). This PR just verified that and adds another assertion.

Client side is still missing, I will create an issue for this.

2022-09-20 10:39 UTC, r-peschke commented
The method BaseActionTestCase.assert_history_information itself is wrong in line 386. There must be a line like `assert informations[-1]["information"] is None`. 
But with this change the test motion/test_create_forwarded:test_all_origin_ids_complex fails and I think it must fail ,because both motions tested are changed with the same position (db-Transaction) and therefore with the same `information`.

2022-09-20 10:40 UTC, r-peschke requested changes
The method BaseActionTestCase.assert_history_information itself is wrong in line 386. There must be a line like assert informations[-1]["information"] is None.
But with this change the test motion/test_create_forwarded:test_all_origin_ids_complex fails and I think it must fail ,because both motions tested are changed with the same position (db-Transaction) and therefore with the same information.

2022-09-23 14:05 UTC, jsangmeister commented
you are correct, I changed the test accordingly, since I don't see an easy way to implement this feature without completely changing the history structure

2022-10-12 09:03 UTC, r-peschke approved these changes

2022-10-13 14:16 UTC, merged