Add migration to remove permission 'user.can_see_extra_data'.
OpenSlides/openslides-backend pull request #1464
Opened 2022-09-13 10:02 UTC by reiterl

2022-09-14 09:23 UTC, r-peschke approved these changes
user.can_see or user.can_manage is present in all groups we create (example_data and meeting.create), so we don't have to replace user.can_see_extra_data by user.can_see

2022-09-15 06:53 UTC, jsangmeister requested changes

2022-09-15 06:53 UTC, jsangmeister commented on openslides_backend/migrations/migrations/0029_remove_permission_user_can_see_extra_data.py
> +            mark = False
you can remove this `mark` handling and just always return `[event]`, since this is just what's used internally in case `None` is returned.

2022-09-15 08:30 UTC, jsangmeister approved these changes

2022-09-15 08:35 UTC, merged