Move template field comment_$ into meeting_user
OpenSlides/openslides-backend pull request #1514
Opened 2022-10-27 09:43 UTC by reiterl

Update example data, fix problems with it, update tests.

2022-10-28 11:16 UTC, r-peschke requested changes

2022-11-02 08:11 UTC, reiterl commented on global/meta/models.yml
> +    restriction_mode: B
Changed.

2022-11-02 08:11 UTC, reiterl commented on global/meta/models.yml
> +    restriction_mode: B
Changed.

2022-11-02 08:11 UTC, reiterl commented on global/meta/models.yml
> +    restriction_mode: B
Changed.

2022-11-02 08:12 UTC, reiterl commented on global/meta/models.yml
> +meeting_user:
Use *A*. Changed.

2022-11-02 08:12 UTC, reiterl commented on global/meta/models.yml
> +    to: meeting_user/meeting_id
Added,

2022-11-02 08:12 UTC, reiterl commented on global/meta/models.yml
> +    to: meeting_user/user_id
Added.

2022-11-02 08:12 UTC, reiterl commented on openslides_backend/action/actions/meeting/delete.py
> +        action_data = [
This is no longer necessary. So removed.

2022-11-02 08:13 UTC, reiterl commented on tests/system/action/meeting_user/test_create.py
> +    def test_create(self) -> None:
Removed the included tests.

2022-11-02 09:39 UTC, r-peschke approved these changes

2022-11-09 08:51 UTC, merged