Move assignment_candidate_ids into meeting_user
OpenSlides/openslides-backend pull request #1538
Opened 2022-11-17 13:59 UTC by reiterl

Update model, actions and tests.

2022-11-17 15:36 UTC, r-peschke requested changes

2022-11-18 08:41 UTC, reiterl commented on openslides_backend/presenter/get_user_related_models.py
> +                    candidate_ids = meeting_user.get("assignment_candidate_ids", [])
No, I just want to get the first and only item. But I changed the code, to make it clear.

2022-11-18 08:42 UTC, reiterl commented on openslides_backend/presenter/get_user_related_models.py
>              if meeting_users:
meeting_users can be an empty dict and I ran into an error if I missed the initialization here.

2022-11-21 18:11 UTC, r-peschke approved these changes
If you want you can merge, but check the comment

2022-11-22 11:18 UTC, reiterl commented on openslides_backend/action/actions/motion/create_base.py
> +            meeting_user = self.datastore.filter(
I will do that later.

2022-11-22 12:04 UTC, merged