Move template field projection ids into meeting_user
OpenSlides/openslides-backend pull request #1539
Opened 2022-11-17 14:02 UTC by reiterl

Update model, actions, tests

2022-11-17 15:28 UTC, r-peschke requested changes
just a very small one;-)

2022-11-17 15:28 UTC, r-peschke commented on openslides_backend/action/actions/meeting/export_helper.py
> +                    if collection_from_fqid(entry[field_name]) == "meeting_user":
elif instead if: can't be both

2022-11-17 15:37 UTC, r-peschke requested changes

2022-11-18 08:48 UTC, reiterl commented on openslides_backend/presenter/get_user_related_models.py
>              if meeting_users:
See 1538.

2022-11-18 08:48 UTC, reiterl commented on openslides_backend/presenter/get_user_related_models.py
> +                    candidate_ids = meeting_user.get("assignment_candidate_ids", [])
See 1538

2022-11-18 09:14 UTC, reiterl commented on openslides_backend/action/actions/meeting/export_helper.py
> +                    if collection_from_fqid(entry[field_name]) == "meeting_user":
Done.

2022-11-21 18:18 UTC, r-peschke approved these changes

2022-11-21 18:18 UTC, r-peschke commented on openslides_backend/models/models.py
> -MODELS_YML_CHECKSUM = "fa09f258347319e4db20d5837bab2a5b"
Must be generated anyway

2022-11-22 12:18 UTC, reiterl commented on openslides_backend/models/models.py
> -MODELS_YML_CHECKSUM = "fa09f258347319e4db20d5837bab2a5b"
Regenerated the models.py

2022-11-22 12:31 UTC, merged