Set password to default password on import
OpenSlides/openslides-backend pull request #1568
Opened 2023-01-06 09:14 UTC by jsangmeister

fixes #1567

2023-01-09 16:54 UTC, r-peschke reviewed
This way is not secure: The importer of the meeting will receive all passwords in uncoded text. IMO we shouldn't do that!
In a final step we should generate a new default_password, set it as initial password and provide the password via secure channel.

2023-01-10 08:56 UTC, jsangmeister commented
> The importer of the meeting will receive all passwords in uncoded text

I don't think this is a problem: To import a meeting, you need to be a committee manager. To see a user's `default_password`, you need to have OML `can_manage_users` or `user.can_manage` in one of the user's meetings. While, strictly speaking, these are separate permissions, it is very likely that many request users will have both requirements fulfilled (and I think the committee manager cannot see users default passwords only because it hasn't come up as a use case, not because there is an inherent security problem with that). So in conclusion, either the importer has the right to see the passwords anyway after importing or it is at least not a problem.

That being said, I see the risk of importing clear-text passwords from a file which might have wandered through anyone's hands. So I'm fine with both solutions - it once again comes down to security vs. convenience ;)

2023-01-10 15:54 UTC, r-peschke requested changes
Please add the following task to this issue:
- don't import default_password, password and last_email_send
-  include a test for these fields

2023-01-10 15:54 UTC, r-peschke commented on openslides_backend/action/actions/meeting/import_.py
> +                if not entry.get("default_password"):
After talking with @emanuelschuetze : Create always a new default_password and set it, i.e. never import the default_password.
We don't need to send the password automatically to the users, the admin will and can select users to send invitation mails.

2023-01-11 16:04 UTC, emanuelschuetze requested changes
I imported a OS3-meeting-export into OS4. Open meeting. Go to participant detail view: the default password is the same as in OS3! But loging does NOT work with old password (OK). Reset of password helps to login successfully.
Expected: new default password should show correctly in detail view.

2023-01-11 16:31 UTC, emanuelschuetze approved these changes
After backend restart: Works now for me!

2023-01-11 16:42 UTC, r-peschke approved these changes

2023-01-11 16:43 UTC, merged