Added missing action_worker in datastore checker.
OpenSlides/openslides-backend pull request #1575
Opened 2023-01-11 17:43 UTC by emanuelschuetze

Fixed warning (```Collections in file do not match with models.py. Invalid collections: action_worker.```) from (extensive) datastore checker (button in client on legal notice page) by adding missiong collection `action_worker`.

2023-01-12 10:48 UTC, r-peschke requested changes

2023-01-12 11:22 UTC, jsangmeister commented
I don't think this should be run through the checker at all, but rather removed beforehand

2023-01-12 11:25 UTC, r-peschke commented
@joshua: Yes, it shouldn't be exported at all.

2023-01-12 11:27 UTC, jsangmeister commented
@r-peschke you tagged the wrong person :D

2023-02-01 17:24 UTC, jsangmeister approved these changes

2023-02-02 17:10 UTC, r-peschke approved these changes

2023-02-02 17:18 UTC, merged