Cleanup user projection and fix/rm tests.
OpenSlides/openslides-backend pull request #1605
Opened 2023-01-24 13:30 UTC by reiterl

2023-01-24 13:55 UTC, jsangmeister requested changes

2023-01-24 13:55 UTC, jsangmeister commented on tests/system/action/projector/test_add_to_preview.py
> -    def test_add_to_preview_user(self) -> None:
Keep the test and assert that it fails

2023-01-24 13:55 UTC, jsangmeister commented on tests/system/action/projector/test_project.py
> -    def test_user_as_content_object_okay(self) -> None:
same here

2023-01-24 14:14 UTC, reiterl commented on tests/system/action/projector/test_add_to_preview.py
> -    def test_add_to_preview_user(self) -> None:
Okay. Done.

2023-01-24 14:14 UTC, reiterl commented on tests/system/action/projector/test_project.py
> -    def test_user_as_content_object_okay(self) -> None:
Okay. Done.

2023-01-25 12:59 UTC, jsangmeister requested changes
minor typo, otherwise fine. Can be merged afterwards

2023-01-25 12:59 UTC, jsangmeister commented on tests/system/action/projector/test_project.py
> +            "he collection 'user' is not available for field 'content_object_id' in collection 'projection'."
```suggestion
            "The collection 'user' is not available for field 'content_object_id' in collection 'projection'."
```

2023-01-25 13:15 UTC, reiterl commented on tests/system/action/projector/test_project.py
> +            "he collection 'user' is not available for field 'content_object_id' in collection 'projection'."
Done.

2023-01-25 13:16 UTC, reiterl commented
@jsangmeister merging is blocked, why that?

2023-01-25 13:18 UTC, jsangmeister approved these changes

2023-01-25 13:19 UTC, jsangmeister commented
@reiterl because there were still changes requested, it seems

2023-01-25 13:19 UTC, reiterl commented
Is that new? How has added that feature?

2023-01-25 13:24 UTC, jsangmeister commented
I recently changed the settings to require a PR and prevent directly pushing to main. It seems like GH automatically requires all change requests to be resolved then and I don't see any way to change this, but I don't think its much of a problem.

2023-01-25 13:32 UTC, merged