Fix wording for better translations
OpenSlides/openslides-backend pull request #1609
Opened 2023-01-30 08:17 UTC by jsangmeister

Done in conjunction with the translation cleanup in https://github.com/OpenSlides/openslides-client/pull/1980

2023-01-30 08:27 UTC, r-peschke requested changes
Please fix the checks

2023-01-31 15:45 UTC, r-peschke approved these changes

2023-01-31 20:25 UTC, emanuelschuetze approved these changes

2023-01-31 20:25 UTC, emanuelschuetze commented
client PR is merged.

2023-01-31 20:25 UTC, merged