Fix `motion.set_state` bulk action
OpenSlides/openslides-backend pull request #1624
Opened 2023-02-07 14:02 UTC by jsangmeister

fixes https://github.com/OpenSlides/openslides-backend/issues/1623

2023-02-08 08:29 UTC, r-peschke requested changes
Please fix the tests

2023-02-15 19:51 UTC, emanuelschuetze approved these changes
Tested

2023-02-15 19:51 UTC, emanuelschuetze commented
@r-peschke Please review again and merge.

2023-02-16 13:45 UTC, r-peschke approved these changes

2023-02-16 14:35 UTC, merged