Update test postgres from 11 to 13.
OpenSlides/openslides-backend pull request #1636
Opened 2023-02-14 13:43 UTC by reiterl

2023-02-15 08:12 UTC, r-peschke approved these changes

2023-02-16 09:34 UTC, jsangmeister requested changes
Also change `.github/docker-compose/docker-compose.prod.yml`

2023-02-17 06:46 UTC, reiterl commented
Changed postgres version in .github, too.

2023-02-17 09:46 UTC, r-peschke approved these changes

2023-02-17 09:56 UTC, merged