Change `search_users` presenter
OpenSlides/openslides-backend pull request #1663
Opened 2023-03-09 13:05 UTC by jsangmeister

fixes https://github.com/OpenSlides/openslides-backend/issues/1662

waiting for https://github.com/OpenSlides/openslides-client/issues/2083

2023-03-09 14:13 UTC, jsangmeister commented
Also unified the scope usages - the implementation as integers was unnecessary.

2023-03-10 14:44 UTC, r-peschke requested changes
Please change the class name and merge

2023-03-10 14:44 UTC, r-peschke commented on openslides_backend/presenter/search_users.py
>  class SearchUsersByNameEmail(BasePresenter):
Please rename class also

2023-03-13 12:47 UTC, r-peschke approved these changes

2023-03-14 16:20 UTC, jsangmeister commented
@r-peschke I added some more changes, mostly removing redundancies. I also made the filters hashable to circumvent the detour via tuples for the duplicate detection. Also added more tests for everything.

2023-03-15 09:02 UTC, r-peschke approved these changes

2023-03-16 12:29 UTC, emanuelschuetze requested changes
Tested and found a bug:
If an existing account has no email address (e.g. account with only first and last name: "Max Mustermann") then the account search should NOT match for "Max" and "Mustermann", because email address is not given.

Currently, the empty mail address matches by given first/last name:

```
[{"presenter":"search_users","data":{"permission_type":"meeting","permission_id":5,"search":[{"username":"","first_name":"Max","last_name":"Mustermann","email":""}]}}]
```
response:
```[[[{"id": 24, "username": "MaxMustermann", "first_name": "Max", "last_name": "Mustermann", "email": ""}]]]```

2023-03-20 08:34 UTC, jsangmeister commented
changed to make all fields of the tuple `(first_name, last_name, email)` required.

2023-03-21 11:30 UTC, emanuelschuetze approved these changes
Tested

2023-03-21 15:04 UTC, merged