Issue1742 hide speaker list
OpenSlides/openslides-backend pull request #1744
Opened 2023-06-05 16:35 UTC by r-peschke

separate LoF.can_be_speaker from LoF.can_see, migration to add LoF.can_see explicitly
Projector.is_internal field in models and actions

2023-06-06 08:00 UTC, jsangmeister requested changes

2023-06-06 08:01 UTC, jsangmeister commented
Also, please stick to https://github.com/OpenSlides/OpenSlides/wiki/Development-organization#pull-request-titles-and-commit-messages

2023-06-06 11:52 UTC, r-peschke commented on openslides_backend/migrations/migrations/0041_add_ListOfSpeakers_CAN_SEE_to_group_events.py
renamed

2023-06-06 12:14 UTC, ostcar commented
The models.yml has changed in the main branch.

Could you merge the main branch in the PR so I can use the models.yml from this branch to make the necessary changes in the autoupdate service?

2023-06-06 14:52 UTC, luisa-beerboom commented
I should not be able to set the meetings reference projector to internal or set an internal projector to be the new reference projector. It will break the autopilot.

I can do that right now.

2023-06-06 15:10 UTC, r-peschke commented on openslides_backend/migrations/migrations/0041_add_ListOfSpeakers_CAN_SEE_to_group_events.py
> +            object["permissions"].append("list_of_speakers.can_see")
done

2023-06-07 09:56 UTC, jsangmeister approved these changes

2023-06-07 10:52 UTC, merged