Add meeting_user_id to user.create action result
OpenSlides/openslides-backend pull request #1866
Opened 2023-08-11 08:10 UTC by reiterl

2023-08-14 11:31 UTC, emanuelschuetze approved these changes
tested with new client

2023-08-15 09:00 UTC, jsangmeister requested changes

2023-08-15 11:59 UTC, r-peschke approved these changes
Approved, except changes concerning jsangmeisters comment

2023-08-15 12:48 UTC, reiterl commented on openslides_backend/action/actions/user/create.py
> +        return {"id": instance["id"], "meeting_user_id": meeting_user_id}
Check for the meeting user id. Dont return it, if it is empty.
Add a check for this in one test.

2023-08-15 12:50 UTC, jsangmeister approved these changes

2023-08-15 12:58 UTC, merged