Add model & permission changes for the LoS extension
OpenSlides/openslides-backend pull request #1981
Opened 2023-11-09 12:29 UTC by jsangmeister

Reordered some fields in `organization` to have settings always above relations

2023-11-10 12:16 UTC, r-peschke commented
Why did you reordered the fields? This will complicate the transformation to the relational fields version of the models.yml

2023-11-10 12:27 UTC, r-peschke requested changes
Please revert the reordering of fields

2023-11-13 15:03 UTC, jsangmeister commented
I don't think we should keep the wrong order or that it hinders the relational database migration, but okay

2023-11-13 15:03 UTC, jsangmeister commented
I also included your comments via email @r-peschke

2023-11-14 09:51 UTC, jsangmeister commented
@r-peschke @rrenkert I merged `meeting/list_of_speakers_enable_structure_level_countdowns` into `meeting/list_of_speakers_default_structure_level_time` so that a time of 0 disables countdowns. This is possible again since there is no orga-wide default any more and it is consistent with the intervention feature. Please check.

I also added a check that the group permissions are the same as the ones defined in the `permissions.yml` as it was possible until now that the two diverge without anyone noticing. I don't think it is even a good idea to keep this information redundant and that we should check the valid permissions not via the model enum, but I refrained from changing this for now to reduce the implementation work and focus on the new features.

2023-11-14 16:21 UTC, r-peschke reviewed
What's about the relation personal_note <-> meetig_user?

2023-11-15 10:59 UTC, jsangmeister commented
I did not change anything about the relation. I just added the `equal_fields` (which should have been there from the start and were probably overlooked - all relations in `meeting_user` should only point to models of the same meeting, obviously). This lead to a few minor errors in the tests, which I fixed. What should be removed there?

2023-11-15 11:01 UTC, jsangmeister commented on openslides_backend/action/actions/personal_note/create.py
>                  ],
I just cleaned up this code part. Previously, the relation was set via the `meeting_user` actions, which was error-prone and redundant. Now, the relation is only set by setting the `meeting_user_id` in the personal note.

2023-11-15 11:28 UTC, r-peschke commented
> I did not change anything about the relation. I just added the `equal_fields` (which should have been there from the start and were probably overlooked - all relations in `meeting_user` should only point to models of the same meeting, obviously). This lead to a few minor errors in the tests, which I fixed. What should be removed there?

Nothing else. It was just about the personal_note, see above.

2023-11-15 11:29 UTC, r-peschke approved these changes

2023-11-15 11:29 UTC, r-peschke commented on openslides_backend/action/actions/personal_note/create.py
>                  ],
Sorry, I overlooked that the personal_note will be set in meeting_user by the relation handling and is not needed to set it explicitly.

2023-11-15 11:35 UTC, jsangmeister commented on openslides_backend/action/actions/personal_note/create.py
>                  ],
okay, no problem

2023-11-15 11:38 UTC, merged