svg and json as html/plain working
OpenSlides/openslides-backend pull request #2057
Opened 2023-12-11 14:40 UTC by r-peschke

2023-12-11 15:47 UTC, luisa-beerboom requested changes

2023-12-11 15:47 UTC, luisa-beerboom commented on openslides_backend/action/actions/mediafile/upload.py
>              raise ActionException(f"Cannot guess mimetype for {filename_}.")
There's no test for this case, could you write it? All that needs to happen is that an unknown file extension needs to be used.

2023-12-11 16:55 UTC, luisa-beerboom approved these changes
nice

2023-12-12 09:25 UTC, rrenkert approved these changes

2023-12-12 11:54 UTC, luisa-beerboom approved these changes

2023-12-12 12:32 UTC, merged