Issue2080 Accept ttf-file-extension for mimetype font/sfnt
OpenSlides/openslides-backend pull request #2093
Opened 2024-01-08 12:55 UTC by r-peschke

2024-01-08 13:01 UTC, jsangmeister requested changes
Please add some comments on what is done and why as the procedure for mimetype checking is becoming increasingly complex and difficult to understand.

2024-01-08 14:44 UTC, luisa-beerboom reviewed
I just noticed in ln 102 of `upload.py` it checks a mimetype against "application.json". Wouldn't that have to be "application/json" to have any effect?

2024-01-08 14:44 UTC, luisa-beerboom commented on openslides_backend/action/actions/mediafile/upload.py
> +                )
What does this code do?

2024-01-08 18:23 UTC, r-peschke commented
> I just noticed in ln 102 of `upload.py` it checks a mimetype against "application.json". Wouldn't that have to be "application/json" to have any effect?

Yes you are right!
This case now is resolved with the pygments.lexers

2024-01-08 18:26 UTC, r-peschke commented
> Please add some comments on what is done and why as the procedure for mimetype checking is becoming increasingly complex and difficult to understand.

I think I guess what you are asking for. Let's talk about tomorrow!

2024-01-09 14:25 UTC, jsangmeister approved these changes

2024-01-09 15:23 UTC, merged