Don't use structure level timer for interposed questions and interventions
OpenSlides/openslides-backend pull request #2126
Opened 2024-01-18 14:51 UTC by jsangmeister

fixes https://github.com/OpenSlides/openslides-backend/issues/2123

2024-01-19 08:38 UTC, r-peschke approved these changes

2024-01-19 17:17 UTC, Elblinator requested changes
the intervention time is still being subtracted from the (remaining) displayed time

If an intervention is selected, the correct time is displayed and only the intervention timer counts down (correct behaviour)
But if you stop the intervention the time from the intervention is subtracted from the displayed timer from the structure level

2024-01-22 09:15 UTC, jsangmeister commented
Fixed this and the analogous problem when pausing an interposed question/intervention with a structure level.

2024-01-22 13:53 UTC, Elblinator approved these changes

2024-01-22 13:55 UTC, merged