Make participant import create structure levels
OpenSlides/openslides-backend pull request #2148
Opened 2024-01-24 16:27 UTC by luisa-beerboom

Closes #2147 

For now I covered the edge case of "What if the corresponding structure level is created between json_upload and import?" by letting the import fail (i.e. forcing the user to start anew) , I could probably make it so that it succeeds instead with the field being switched over to an update field, what do you think @rrenkert ?

2024-01-25 08:34 UTC, jsangmeister requested changes
Code looks fine, but IMO we should not fail with an error if a structure level was created in the meantime but just use it, as you already proposed

2024-01-25 10:06 UTC, luisa-beerboom commented
> Code looks fine, but IMO we should not fail with an error if a structure level was created in the meantime but just use it, as you already proposed

Done

2024-01-25 10:24 UTC, jsangmeister requested changes

2024-01-30 07:51 UTC, jsangmeister approved these changes

2024-01-30 08:30 UTC, merged