Allow import for existing users with legacy usernames
OpenSlides/openslides-backend pull request #2211
Opened 2024-02-13 14:46 UTC by jsangmeister

fixes #2204

2024-02-14 08:44 UTC, luisa-beerboom requested changes

2024-02-14 08:44 UTC, luisa-beerboom commented on tests/system/action/base.py
> +        self, meeting_id: int, username: str | None = None
username parameter isn't used, remove it

2024-02-14 09:30 UTC, r-peschke approved these changes

2024-02-15 09:22 UTC, luisa-beerboom approved these changes

2024-02-15 09:36 UTC, merged