Implement cascade delete for amendments
OpenSlides/openslides-backend pull request #2253
Opened 2024-02-27 13:32 UTC by luisa-beerboom

Closes #2251 
See OpenSlides/openslides-meta#37

2024-02-28 11:14 UTC, r-peschke approved these changes

2024-02-29 13:09 UTC, Elblinator requested changes
Deleting a motion and some/all of it's amendments via multi-select create the following Error: 
```
Error: Datastore service sends HTTP 400. Model 'motion/16' does not exist.
```

send request: 
```
[
    {
        "action": "motion.delete",
        "data": [
            {
                "id": 15
            },
            {
                "id": 16
            }
        ]
    }
]
```

2024-03-04 09:08 UTC, r-peschke approved these changes

2024-03-04 10:04 UTC, Elblinator approved these changes

2024-03-04 11:10 UTC, merged