Add remaining_time to SlLoS.update
OpenSlides/openslides-backend pull request #2279
Opened 2024-03-08 10:05 UTC by luisa-beerboom

Closes #2219

2024-03-08 10:45 UTC, jsangmeister requested changes

2024-03-08 10:45 UTC, jsangmeister commented on tests/system/action/structure_level_list_of_speakers/test_update.py
> +            internal=True,
Please remove the `internal=True`, this should be callable from the client

2024-03-12 09:00 UTC, jsangmeister requested changes
If the `remaining_time` is updated while `current_start_time` is not `None` (meaning some speaker is currently speaking for the structure level), the difference between the old and the new remaining time must be added/substracted from the `current_start_time`

2024-03-13 07:43 UTC, jsangmeister requested changes

2024-03-13 07:43 UTC, jsangmeister commented on openslides_backend/action/actions/structure_level_list_of_speakers/update.py
>              instance["remaining_time"] = instance["initial_time"]
`current_start_time` also needs to be changed if `remaining_time` is changed by changing the `initial_time`

2024-03-13 07:43 UTC, jsangmeister commented on openslides_backend/action/actions/structure_level_list_of_speakers/update.py
>              )
You could fetch the `db_instance` once at the start to deduplicate and streamline the code

2024-03-13 09:10 UTC, jsangmeister approved these changes

2024-03-13 09:11 UTC, jsangmeister commented
@Elblinator please test if this fixes your countdown issues in the client

2024-03-14 09:39 UTC, luisa-beerboom commented
> If the `remaining_time` is updated while `current_start_time` is not `None` (meaning some speaker is currently speaking for the structure level), the difference between the old and the new remaining time must be added/substracted from the `current_start_time`

After speaking with @Elblinator this change is to be reverted

2024-03-14 14:17 UTC, Elblinator approved these changes
LGTM, it's awesome! 

But please fix your tests :)

2024-03-14 14:25 UTC, jsangmeister approved these changes

2024-03-18 08:42 UTC, merged