Setup tests for relational database schema
OpenSlides/openslides-backend pull request #2421
Opened 2024-05-15 12:30 UTC by r-peschke

2024-05-30 15:11 UTC, rrenkert approved these changes

2024-08-23 09:04 UTC, reicda requested changes
- Autocommit should be set to True as there is a need for transactions containing multiple commands.
- There are some casings that can be improved for a better readability.
- Everything else looks fine to me.

2024-08-23 12:43 UTC, r-peschke commented on openslides_backend/database/db_connection_handling.py
see conclusion comment from @reicda to stay with autocommit=True

2024-08-23 12:47 UTC, r-peschke commented on tests/datastore/reader/system/history_information/test_history_information.py
done

2024-08-23 12:49 UTC, r-peschke commented on tests/datastore/reader/system/history_information/test_history_information.py
done

2024-08-23 12:51 UTC, r-peschke commented on tests/datastore/writer/system/test_write_action_worker.py
done

2024-08-23 12:59 UTC, r-peschke commented on tests/datastore/writer/system/util.py
done

2024-08-23 13:02 UTC, r-peschke commented on tests/datastore/writer/system/write/test_create.py
done

2024-08-23 13:05 UTC, r-peschke commented on tests/datastore/writer/system/write/test_migration_index.py
done

2024-08-23 13:07 UTC, r-peschke commented on tests/datastore/writer/system/write/test_writerequest_data.py
done

2024-08-26 08:05 UTC, reicda approved these changes

2024-08-26 12:46 UTC, merged