Allow additional submitters update with CAN_MANAGE_METADATA
OpenSlides/openslides-backend pull request #2439
Opened 2024-05-22 11:37 UTC by bastianjoel

2024-05-23 07:01 UTC, luisa-beerboom requested changes
In general changes to actions and presenters should be accompanied by the underlying changes in the docs (under openslides-backend/docs)

2024-05-24 07:26 UTC, bastianjoel commented on openslides_backend/presenter/get_forwarding_committees.py
> +            msg += f" Missing permission: {Permissions.Motion.CAN_MANAGE_METADATA}"
> User with the group permission 'can manage motion metadata' should be able to see and edit the committee field.

Last point in the client issue.

2024-05-24 07:34 UTC, bastianjoel commented
There is no doc for that presenter.

2024-05-27 07:30 UTC, luisa-beerboom requested changes
Only change the wiki entry of the motion update then, I'll create an issue for the presenter

2024-05-28 07:13 UTC, luisa-beerboom approved these changes

2024-05-28 07:27 UTC, merged