Removed member_number name generation from user imports
OpenSlides/openslides-backend pull request #2476
Opened 2024-06-07 10:27 UTC by luisa-beerboom

Closes #2474

2024-06-07 10:56 UTC, MSoeb approved these changes

2024-06-07 11:53 UTC, Elblinator requested changes
Only the first Error is shown in the preview
In the following screenshot every line is a user I tried to create via only the member number
![Screenshot_20240607_135218](https://github.com/OpenSlides/openslides-backend/assets/69210919/7afba9d0-5218-40b4-9ce1-c6d26b08c518)

2024-06-07 11:59 UTC, r-peschke approved these changes
Seems to be correct, but we really should refactor the validate_entry code!

2024-06-10 08:34 UTC, r-peschke approved these changes

2024-06-10 10:28 UTC, Elblinator approved these changes

2024-06-10 10:44 UTC, merged