Implement motion_change_recommendation creation in motion forward
OpenSlides/openslides-backend pull request #2549
Opened 2024-08-02 15:09 UTC by luisa-beerboom

Closes #2519 

TODO:
- [x] Test with less attributes filled
- [x] Test with no change recommendations in db, but flag set
- [x] Test with change recos in db but no flag set
- [x] Test with amendments

2024-08-05 10:06 UTC, bastianjoel requested changes
Please update documentation

2024-08-05 10:28 UTC, luisa-beerboom commented
> Please update documentation

Done

2024-08-05 11:33 UTC, bastianjoel approved these changes
Docs look good now

2024-08-08 09:27 UTC, hjanott approved these changes

2024-08-08 09:27 UTC, hjanott commented on tests/system/action/motion/test_create_forwarded.py
> +        reco = self.assert_model_exists(
`reco` isn't used after this line.

2024-08-08 09:27 UTC, hjanott commented on tests/system/action/motion/test_create_forwarded.py
> +        reco = self.assert_model_exists(
`reco` isn't used after this line.

2024-08-08 13:39 UTC, merged