Remove can_see from can_see_moderator_note
OpenSlides/openslides-backend pull request #2593
Opened 2024-09-04 15:32 UTC by luisa-beerboom

Closes #2592 

TODO: 
- [ ] migration!
- [ ] fix agenda_item.update test

2024-09-10 12:59 UTC, hjanott approved these changes

2024-09-23 15:14 UTC, m-schieder requested changes
[backendmanage]  ERROR:openslides_backend.shared.handlers.base_handler:'NoneType' object is not iterable
[backendmanage]  Traceback (most recent call last):
[backendmanage]  File "/app/openslides_backend/migrations/migration_handler.py", line 102, in execute_migrate_command
[backendmanage]  return handler.execute_command(command)
[backendmanage]  File "/app/openslides_backend/migrations/migration_wrapper.py", line 76, in execute_command
[backendmanage]  self.handler.finalize()
[backendmanage]  File "/usr/local/lib/python3.10/site-packages/datastore/migrations/core/migration_handler.py", line 291, in finalize
[backendmanage]  self.model_migrater.migrate()
[backendmanage]  File "/usr/local/lib/python3.10/site-packages/datastore/migrations/core/migraters/model_migrater.py", line 29, in migrate
[backendmanage]  events = migration.migrate(self.reader)
[backendmanage]  File "/usr/local/lib/python3.10/site-packages/datastore/migrations/core/base_migrations/base_model_migration.py", line 16, in migrate
[backendmanage]  return self.migrate_models()
[backendmanage]  File "/app/openslides_backend/migrations/migrations/0056_move_moderator_notes.py", line 66, in migrate_models
[backendmanage]  [
[backendmanage]  File "/app/openslides_backend/migrations/migrations/0056_move_moderator_notes.py", line 97, in <listcomp>
[backendmanage]  perm_substrings := [
[backendmanage]  File "/app/openslides_backend/migrations/migrations/0056_move_moderator_notes.py", line 103, in <listcomp>
[backendmanage]  if any(
[backendmanage]  TypeError: 'NoneType' object is not iterable

2024-09-30 15:27 UTC, hjanott commented on tests/system/migrations/test_0058_move_moderator_notes.py
> +            "fqid": "group/10",
You are not doing the assert_model for this group.

2024-10-01 07:07 UTC, hjanott approved these changes

2024-10-11 10:05 UTC, m-schieder approved these changes

2024-10-17 10:28 UTC, merged