add new meeting specific setting hide metadata background for projector
OpenSlides/openslides-backend pull request #2647
Opened 2024-09-25 14:41 UTC by hjanott

Closes #2642

2024-09-26 07:25 UTC, luisa-beerboom requested changes

2024-09-26 07:25 UTC, luisa-beerboom commented on global/data/example-data.json
> +            "motions_hide_metadata_background": true,
Why not use the default?

2024-09-26 07:25 UTC, luisa-beerboom commented on openslides_backend/action/actions/meeting/update.py
> +    "motions_hide_metadata_background",
Add the field to one of the tests

2024-09-27 10:26 UTC, hjanott commented on global/data/example-data.json
> +            "motions_hide_metadata_background": true,
I changed the value to false.

2024-09-27 10:26 UTC, hjanott commented on openslides_backend/action/actions/meeting/update.py
> +    "motions_hide_metadata_background",
added

2024-09-27 11:46 UTC, Elblinator approved these changes

2024-09-27 13:53 UTC, luisa-beerboom approved these changes

2024-09-27 15:01 UTC, merged