Update motion.update: Add attachment_ids and workflow code.
OpenSlides/openslides-backend pull request #449
Opened 2021-02-08 12:10 UTC by reiterl

Add this code from motion.update_metadata.
Also update and add tests.

**Notice**: The origin field stays out. I'm not sure about that field.

2021-02-11 08:29 UTC, jsangmeister requested changes

2021-02-11 08:29 UTC, jsangmeister commented on tests/system/action/motion/test_update.py
> +                            "supporter_ids": [],
Please also add a test where you set these fields.

2021-02-11 09:59 UTC, jsangmeister commented
Also, `origin_id` has to be handled the same way as in `motion.create` - you can reuse the check from that action.

2021-02-11 10:37 UTC, FinnStutzenstein commented
Please first wait for the discussion in https://github.com/OpenSlides/openslides-backend-coordination/issues/25

2021-03-04 09:49 UTC, jsangmeister commented
See https://github.com/OpenSlides/openslides-backend/issues/487: please merge this PR with #448 and fuse the actions together.

2021-03-12 09:27 UTC, closed without merging

2021-03-12 09:27 UTC, reiterl commented
motion update and update_metadata are merged in another pr.