Add permissions to motion_state. Update tests.
OpenSlides/openslides-backend pull request #618
Opened 2021-03-26 11:58 UTC by reiterl

2021-03-26 13:20 UTC, jsangmeister requested changes
rest looks good

2021-03-26 13:20 UTC, jsangmeister commented on tests/system/action/motion_state/test_create.py
> +
white space seems unnecessary

2021-03-26 13:20 UTC, jsangmeister commented on tests/system/action/motion_state/test_delete.py
> +
see above

2021-03-26 13:20 UTC, jsangmeister commented on tests/system/action/motion_state/test_update.py
> +
see above

2021-04-01 08:04 UTC, reiterl commented on tests/system/action/motion_state/test_create.py
> +
Removed.

2021-04-01 08:04 UTC, reiterl commented on tests/system/action/motion_state/test_delete.py
> +
Removed.

2021-04-01 08:04 UTC, reiterl commented on tests/system/action/motion_state/test_update.py
> +
Removed.

2021-04-01 08:42 UTC, jsangmeister approved these changes

2021-04-01 08:44 UTC, merged