Change default value for lock_result to true
OpenSlides/openslides-backend pull request #674
Opened 2021-04-22 14:18 UTC by jsangmeister

Uses the updated datastore interface (https://github.com/OpenSlides/OpenSlides/pull/6018) to lock collection fields multiple times.

2021-04-26 09:14 UTC, r-peschke requested changes

2021-04-26 11:53 UTC, jsangmeister commented on openslides_backend/action/action.py
> -            self.datastore.locked_fields = {}
You are correct. Fixed it.

2021-04-26 13:16 UTC, jsangmeister commented
@r-peschke I thought about this again really hard and think this is the correct way to do it. Previously, we locked an reset at the wrong place since actions can be nested. So the action handler should be doing this at the end. Also, in atomic mode, it is correct to keep the locked fields since the transaction is executed at once and should fail if any locks are broken. Please check the new changes.

2021-05-03 08:32 UTC, r-peschke approved these changes

2021-05-03 14:11 UTC, merged