Fix a bug: clean voted_ids at poll.reset. Add a test.
OpenSlides/openslides-backend pull request #753
Opened 2021-06-07 12:18 UTC by reiterl

2021-06-07 12:41 UTC, jsangmeister requested changes
Please also add an assert to the `test_reset_correct` that the `voted_ids` are cleared.

2021-06-08 06:48 UTC, reiterl commented
Add an assert to test_reset_correct.

2021-06-08 11:16 UTC, jsangmeister approved these changes

2021-06-08 19:53 UTC, FinnStutzenstein approved these changes

2021-06-09 08:52 UTC, merged