Issue774:Remove user.create check for OML, CML or group-permission
OpenSlides/openslides-backend pull request #775
Opened 2021-06-14 10:46 UTC by r-peschke

2021-06-14 11:39 UTC, jsangmeister requested changes

2021-06-14 11:39 UTC, jsangmeister commented on openslides_backend/action/actions/user/create.py
> +        #     )
Please remove instead of commenting out

2021-06-15 07:26 UTC, r-peschke commented on openslides_backend/action/actions/user/create.py
> +        #     )
Done

2021-06-15 08:01 UTC, jsangmeister approved these changes

2021-06-15 08:54 UTC, merged