Issue868 Fix missing is_present_in_meetings and can_change_own_password
OpenSlides/openslides-backend pull request #873
Opened 2021-07-28 09:30 UTC by r-peschke

2021-07-28 09:34 UTC, FinnStutzenstein approved these changes

2021-07-28 11:16 UTC, jsangmeister requested changes
`is_demo_user` is missing for `user.create`, rest looks good

2021-07-29 06:43 UTC, emanuelschuetze approved these changes

2021-07-29 07:08 UTC, jsangmeister approved these changes

2021-07-29 07:40 UTC, merged