Fix ordering error for calculated field handlers
OpenSlides/openslides-backend pull request #875
Opened 2021-07-29 10:00 UTC by jsangmeister

fixes #869

2021-07-29 12:02 UTC, r-peschke requested changes

2021-07-30 09:34 UTC, jsangmeister commented on openslides_backend/action/relations/meeting_user_ids_handler.py
> +        # check if removed_ids should actually be removed
The handler is only called for the field `group/user_ids`, the meeting parts are a relict from the previous user structure with guest users etc. Thank you for the hint, will remove it

2021-07-30 09:49 UTC, r-peschke approved these changes

2021-07-30 09:56 UTC, jsangmeister commented
The CI does not work:
```
E: Failed to fetch https://deb.nodesource.com/node_14.x/pool/main/n/nodejs/nodejs_14.17.4-1nodesource1_amd64.deb  File has unexpected size (25211968 != 25045506). Mirror sync in progress? [IP: 23.62.230.72 443]
   Hashes of expected file:
    - SHA256:796a1b5f6fa3caddd4b1f6e31bb8e98a1f289dae638a17d41ec73be0d080eceb
    - SHA1:d7e7966ad5ba47486a307d33b61b637e11c87335 [weak]
    - MD5Sum:2c4e16dcadfed0711d1a3192da4c6d1e [weak]
    - Filesize:25045506 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Service 'auth' failed to build : The command '/bin/sh -c apt-get install -y nodejs' returned a non-zero code: 100
```
Restarting did not help. Does anyone have an idea what might fix this?

2021-07-30 10:02 UTC, jsangmeister commented
Seems like this is a general problem, in https://github.com/OpenSlides/openslides-backend/pull/861 the same error occured after restarting the jobs.

2021-07-30 11:29 UTC, reiterl commented
I try another restart, perhaps a temp problem.

2021-08-02 07:01 UTC, merged